# Copyright 2021 Dell Inc, or its subsidiaries.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-random-temperature
  labels:
    app.kubernetes.io/app: device-random-temperature
    app.kubernetes.io/part-of: edgex-foundry
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: device-random-temperature
      app.kubernetes.io/part-of: edgex-foundry
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/app: device-random-temperature
        app.kubernetes.io/part-of: edgex-foundry
      name: device-random-temperature
    spec:
      containers:
      - command:
        - /device-random-temperature
        envFrom:
        - configMapRef:
            name: edgex-common-env
        env:
        - name: Service_Host
          value: "device-random-temperature"
        - name: Service_Port
          value: "49988"
        image: device-random-temperature-go:latest
        imagePullPolicy: IfNotPresent
        name: device-random-temperature
        ports:
        - containerPort: 49988
