apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/app: device-random-temperature
    app.kubernetes.io/part-of: edgex-foundry
  name: device-random-temperature
  namespace: default
spec:
  ports:
  - port: 49988
    targetPort: 49988
  selector:
    app.kubernetes.io/app: device-random-temperature
    app.kubernetes.io/part-of: edgex-foundry